server:
  port: 9101
spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone: http://111.231.77.198:8000/eureka/,http://111.231.77.198:8000/eureka/

#zuul:..
#  prefix: /imooc
#  routes:
#    course:
#      path: /homepage-course/**
#      serviceId: eureka-client-homepage-course
#      strip-prefix: false
#    user:
#      path: /homepage-user/**
#      serviceId: eureka-client-homepage-user
#      strip-prefix: false
