spring:
  application:
    name: eureka

server:
  port: 8000

eureka:
  instance:
    hostname: 111.231.77.198
    #设置使用IP
    prefer-ip-address: true
    #设置外网IP号
    ip-address: 111.231.77.198
    #设置外网端口号
    non-secure-port: 8000
    instance-id: http://111.231.77.198:7003
  client:
    register-with-eureka: false
    fetch-registry: false
    # eureka.client.fetch-registry: 表示是否从 Eureka Server 获取注册信息，默认为true。如果这是一个单点的 Eureka Server，不需要同步其他节点的数据，设为false
    #nfetch-registry: false
    # eureka.client.register-with-eureka: 表示是否将自己注册到 Eureka Server, 默认为true。由于当前应用就是 Eureka Server, 因此设为 false
    # register-with-eureka: false
    # 设置 Eureka Server 所在的地址，查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

